class himasHospitalRunner{
public static void main(String[]websites){
if(himasHospital.bookConsultation!=false){
	himasHospital.getCustomerDetails();
	
boolean patient1 = himasHospital.bookConsultation("Rahul","Sharma",9876543210L,"rahul.sharma@gmail.com","Fever","IDM1001","B+",28);
        himasHospital.getCustomerDetails();
boolean patient2 = himasHospital.bookConsultation("Priya","Reddy",9988776655L,"priya.reddy@gmail.com","Headache","IDM1002","O+",24);
        himasHospital.getCustomerDetails();
boolean patient3 = himasHospital.bookConsultation("Arjun","Patil",9123456789L,"arjun.patil@gmail.com","Cough","IDM1003","A+",35);
        himasHospital.getCustomerDetails();
boolean patient4 = himasHospital.bookConsultation("Sneha","Nair",9012345678L,"sneha.nair@gmail.com","Cold","IDM1004","AB+",30);
        himasHospital.getCustomerDetails();
boolean patient5 = himasHospital.bookConsultation("Karthik","Gowda",8899776655L,"karthik.gowda@gmail.com","Fever","IDM1005","O-",22);
        himasHospital.getCustomerDetails();
boolean patient6 = himasHospital.bookConsultation("Ananya","Joshi",9345678901L,"ananya.joshi@gmail.com","Skin Allergy","IDM1006","A-",27);
        himasHospital.getCustomerDetails();
boolean patient7 = himasHospital.bookConsultation("Vikram","Singh",9765432109L,"vikram.singh@gmail.com","Back Pain","IDM1007","B-",41);
        himasHospital.getCustomerDetails();
boolean patient8 = himasHospital.bookConsultation("Meera","Iyer",9845012345L,"meera.iyer@gmail.com","Migraine","IDM1008","AB-",33);
        himasHospital.getCustomerDetails();
boolean patient9 = himasHospital.bookConsultation("Rohit","Kumar",9871234567L,"rohit.kumar@gmail.com","Diabetes","IDM1009","O+",46);
        himasHospital.getCustomerDetails();
boolean patient10 = himasHospital.bookConsultation("Pooja","Kulkarni",9900112233L,"pooja.kulkarni@gmail.com","Eye Infection","IDM1010","A+",29);
        himasHospital.getCustomerDetails();
boolean patient11 = himasHospital.bookConsultation("Aditya","Verma",9876501234L,"aditya.verma@gmail.com","Fever","IDM1011","B+",31);
        himasHospital.getCustomerDetails();
boolean patient12 = himasHospital.bookConsultation("Neha","Gupta",9123004567L,"neha.gupta@gmail.com","Cold","IDM1012","O+",26);
        himasHospital.getCustomerDetails();
boolean patient13 = himasHospital.bookConsultation("Suresh","Yadav",9988123456L,"suresh.yadav@gmail.com","Asthma","IDM1013","A+",48);
        himasHospital.getCustomerDetails();
boolean patient14 = himasHospital.bookConsultation("Deepa","Shetty",9345612345L,"deepa.shetty@gmail.com","Stomach Pain","IDM1014","B-",32);
        himasHospital.getCustomerDetails();
boolean patient15 = himasHospital.bookConsultation("Harish","Rao",9845123490L,"harish.rao@gmail.com","Fever","IDM1015","AB+",37);
        himasHospital.getCustomerDetails();
boolean patient16 = himasHospital.bookConsultation("Nikhil","Bhat",9011122233L,"nikhil.bhat@gmail.com","Cough","IDM1016","O-",25);
        himasHospital.getCustomerDetails();
boolean patient17 = himasHospital.bookConsultation("Lakshmi","Menon",9888777665L,"lakshmi.menon@gmail.com","Headache","IDM1017","A-",39);
        himasHospital.getCustomerDetails();
boolean patient18 = himasHospital.bookConsultation("Manoj","Naik",9877001122L,"manoj.naik@gmail.com","Typhoid","IDM1018","B+",43);
        himasHospital.getCustomerDetails();
boolean patient19 = himasHospital.bookConsultation("Divya","Mishra",9001234567L,"divya.mishra@gmail.com","Fever","IDM1019","O+",21);
        himasHospital.getCustomerDetails();
boolean patient20 = himasHospital.bookConsultation("Ganesh","Desai",9898981234L,"ganesh.desai@gmail.com","Cold","IDM1020","AB-",34);
        himasHospital.getCustomerDetails();
boolean patient21 = himasHospital.bookConsultation("Akhil","Hegde",9123450001L,"akhil.hegde@gmail.com","Back Pain","IDM1021","B+",29);
        himasHospital.getCustomerDetails();
boolean patient22 = himasHospital.bookConsultation("Bhavana","Rana",9345600002L,"bhavana.rana@gmail.com","Migraine","IDM1022","O-",31);
        himasHospital.getCustomerDetails();
boolean patient23 = himasHospital.bookConsultation("Chandan","Das",9876000003L,"chandan.das@gmail.com","Fever","IDM1023","A+",36);
        himasHospital.getCustomerDetails();
boolean patient24 = himasHospital.bookConsultation("Dinesh","Mali",9988700004L,"dinesh.mali@gmail.com","Diabetes","IDM1024","B-",50);
        himasHospital.getCustomerDetails();
boolean patient25 = himasHospital.bookConsultation("Esha","Kapoor",9765400005L,"esha.kapoor@gmail.com","Cold","IDM1025","AB+",23);
        himasHospital.getCustomerDetails();
boolean patient26 = himasHospital.bookConsultation("Farhan","Ali",9012300006L,"farhan.ali@gmail.com","Cough","IDM1026","O+",28);
        himasHospital.getCustomerDetails();
boolean patient27 = himasHospital.bookConsultation("Geetha","Acharya",9345700007L,"geetha.acharya@gmail.com","Skin Allergy","IDM1027","A-",45);
        himasHospital.getCustomerDetails();
boolean patient28 = himasHospital.bookConsultation("Hemant","Pandey",9876100008L,"hemant.pandey@gmail.com","Fever","IDM1028","B+",40);
        himasHospital.getCustomerDetails();
boolean patient29 = himasHospital.bookConsultation("Ishita","Saxena",9988800009L,"ishita.saxena@gmail.com","Eye Pain","IDM1029","AB-",27);
        himasHospital.getCustomerDetails();
boolean patient30 = himasHospital.bookConsultation("Jeevan","Kulal",9123400010L,"jeevan.kulal@gmail.com","Headache","IDM1030","O-",33);
        himasHospital.getCustomerDetails();
boolean patient31 = himasHospital.bookConsultation("Kavya","Murthy",9345800011L,"kavya.murthy@gmail.com","Fever","IDM1031","A+",24);
        himasHospital.getCustomerDetails();
boolean patient32 = himasHospital.bookConsultation("Lokesh","Pillai",9876200012L,"lokesh.pillai@gmail.com","Cold","IDM1032","B-",38);
        himasHospital.getCustomerDetails();
boolean patient33 = himasHospital.bookConsultation("Madhu","Krishnan",9988900013L,"madhu.krishnan@gmail.com","Asthma","IDM1033","O+",44);
        himasHospital.getCustomerDetails();
boolean patient34 = himasHospital.bookConsultation("Naveen","Chauhan",9123500014L,"naveen.chauhan@gmail.com","Cough","IDM1034","AB+",35);
        himasHospital.getCustomerDetails();
boolean patient35 = himasHospital.bookConsultation("Oviya","Raj",9345900015L,"oviya.raj@gmail.com","Fever","IDM1035","A-",22);
        himasHospital.getCustomerDetails();
boolean patient36 = himasHospital.bookConsultation("Prakash","Jain",9876300016L,"prakash.jain@gmail.com","Back Pain","IDM1036","B+",47);
        himasHospital.getCustomerDetails();
boolean patient37 = himasHospital.bookConsultation("Qasim","Khan",9988000017L,"qasim.khan@gmail.com","Cold","IDM1037","O-",30);
        himasHospital.getCustomerDetails();
boolean patient38 = himasHospital.bookConsultation("Ramesh","Chandra",9123600018L,"ramesh.chandra@gmail.com","Diabetes","IDM1038","A+",52);
        himasHospital.getCustomerDetails();
boolean patient39 = himasHospital.bookConsultation("Shilpa","Bora",9345000019L,"shilpa.bora@gmail.com","Migraine","IDM1039","AB-",26);
        himasHospital.getCustomerDetails();
boolean patient40 = himasHospital.bookConsultation("Tarun","Mehta",9876400020L,"tarun.mehta@gmail.com","Fever","IDM1040","B-",34);
        himasHospital.getCustomerDetails();
boolean patient41 = himasHospital.bookConsultation("Usha","Pawar",9988100021L,"usha.pawar@gmail.com","Cold","IDM1041","O+",42);
        himasHospital.getCustomerDetails();
boolean patient42 = himasHospital.bookConsultation("Varun","Solanki",9123700022L,"varun.solanki@gmail.com","Cough","IDM1042","A+",28);
        himasHospital.getCustomerDetails();
boolean patient43 = himasHospital.bookConsultation("Waseem","Shaikh",9345100023L,"waseem.shaikh@gmail.com","Skin Allergy","IDM1043","B+",37);
        himasHospital.getCustomerDetails();
boolean patient44 = himasHospital.bookConsultation("Yash","Thakur",9876500024L,"yash.thakur@gmail.com","Headache","IDM1044","AB+",25);
        himasHospital.getCustomerDetails();
boolean patient45 = himasHospital.bookConsultation("Zoya","Ansari",9988200025L,"zoya.ansari@gmail.com","Fever","IDM1045","O-",23);
        himasHospital.getCustomerDetails();
boolean patient46 = himasHospital.bookConsultation("Abhishek","Mohan",9123800026L,"abhishek.mohan@gmail.com","Typhoid","IDM1046","A-",39);
        himasHospital.getCustomerDetails();
boolean patient47 = himasHospital.bookConsultation("Bindu","Ramesh",9345200027L,"bindu.ramesh@gmail.com","Cold","IDM1047","B+",41);
        himasHospital.getCustomerDetails();
boolean patient48 = himasHospital.bookConsultation("Chetan","Kamble",9876600028L,"chetan.kamble@gmail.com","Back Pain","IDM1048","O+",36);
         himasHospital.getCustomerDetails();
boolean patient49 = himasHospital.bookConsultation("Deeksha","Patel",9988300029L,"deeksha.patel@gmail.com","Fever","IDM1049","AB-",27);
        himasHospital.getCustomerDetails();
boolean patient50 = himasHospital.bookConsultation("Eshwar","Rathod",9123900030L,"eshwar.rathod@gmail.com","Asthma","IDM1050","A+",49);
        himasHospital.getCustomerDetails();
   }
else{
		System.out.println("the file not found");
}
}
}