class LibraryRunner{
public static void main(String[] websites){

boolean member1 = Library.issueBook("Aarush","Singhania",9874512301L,"aarush.singhania@gmail.com","The Alchemist","MID1001","Fiction",20);
        Library.getMemberDetails();
boolean member2 = Library.issueBook("Kiya","Bhardwaj",9123487602L,"kiya.bhardwaj@gmail.com","Atomic Habits","MID1002","Self Help",21);
        Library.getMemberDetails();
boolean member3 = Library.issueBook("Vivit","Agarwal",9345612703L,"vivit.agarwal@gmail.com","Wings of Fire","MID1003","Biography",22);
        Library.getMemberDetails();
boolean member4 = Library.issueBook("Anvi","Chauhan",9012876504L,"anvi.chauhan@gmail.com","Rich Dad Poor Dad","MID1004","Finance",19);
        Library.getMemberDetails();
boolean member5 = Library.issueBook("Rudransh","Saxena",8899765405L,"rudransh.saxena@gmail.com","Clean Code","MID1005","Technology",20);
        Library.getMemberDetails();
boolean member6 = Library.issueBook("Mysha","Rastogi",9345789006L,"mysha.rastogi@gmail.com","Harry Potter","MID1006","Fantasy",21);
        Library.getMemberDetails();
boolean member7 = Library.issueBook("Lakshit","Khurana",9765123407L,"lakshit.khurana@gmail.com","Think and Grow Rich","MID1007","Self Help",22);
        Library.getMemberDetails();
boolean member8 = Library.issueBook("Navisha","Gulati",9845234508L,"navisha.gulati@gmail.com","Data Structures","MID1008","Education",20);
        Library.getMemberDetails();
boolean member9 = Library.issueBook("Yashit","Puri",9871345609L,"yashit.puri@gmail.com","Java Programming","MID1009","Technology",23);
        Library.getMemberDetails();
boolean member10 = Library.issueBook("Trisha","Bansal",9900456710L,"trisha.bansal@gmail.com","Python Crash Course","MID1010","Education",21);
        Library.getMemberDetails();
boolean member11 = Library.issueBook("Abeer","Chitkara",9876567811L,"abeer.chitkara@gmail.com","The Hobbit","MID1011","Fantasy",20);
        Library.getMemberDetails();
boolean member12 = Library.issueBook("Siara","Dhingra",9123678912L,"siara.dhingra@gmail.com","Ikigai","MID1012","Self Help",22);
        Library.getMemberDetails();
boolean member13 = Library.issueBook("Vedansh","Nijhawan",9988789013L,"vedansh.nijhawan@gmail.com","Deep Work","MID1013","Productivity",21);
        Library.getMemberDetails();
boolean member14 = Library.issueBook("Maira","Lal",9345890114L,"maira.lal@gmail.com","The Psychology of Money","MID1014","Finance",23);
        Library.getMemberDetails();
boolean member15 = Library.issueBook("Revaan","Suri",9845901215L,"revaan.suri@gmail.com","Operating Systems","MID1015","Technology",19);
        Library.getMemberDetails();
boolean member16 = Library.issueBook("Ishika","Makkar",9011012316L,"ishika.makkar@gmail.com","Computer Networks","MID1016","Education",22);
        Library.getMemberDetails();
boolean member17 = Library.issueBook("Vihaan","Kohli",9888123417L,"vihaan.kohli@gmail.com","The Silent Patient","MID1017","Thriller",20);
        Library.getMemberDetails();
boolean member18 = Library.issueBook("Nysa","Talreja",9877234518L,"nysa.talreja@gmail.com","The Power of Habit","MID1018","Self Help",21);
        Library.getMemberDetails();
boolean member19 = Library.issueBook("Ariz","Walia",9001345619L,"ariz.walia@gmail.com","Artificial Intelligence","MID1019","Technology",22);
        Library.getMemberDetails();
boolean member20 = Library.issueBook("Samika","Ahuja",9898096720L,"samika.ahuja@gmail.com","Pride and Prejudice","MID1020","Classic",20);
        Library.getMemberDetails();
boolean member21 = Library.issueBook("Dhruv","Bedi",9123400021L,"dhruv.bedi@gmail.com","The Great Gatsby","MID1021","Classic",21);
        Library.getMemberDetails();
boolean member22 = Library.issueBook("Aanya","Chhibber",9345600022L,"aanya.chhibber@gmail.com","The Monk Who Sold His Ferrari","MID1022","Self Help",20);
        Library.getMemberDetails();
boolean member23 = Library.issueBook("Krishiv","Panchal",9876000023L,"krishiv.panchal@gmail.com","The Da Vinci Code","MID1023","Mystery",22);
        Library.getMemberDetails();
boolean member24 = Library.issueBook("Shanaya","Nagpal",9988700024L,"shanaya.nagpal@gmail.com","Zero to One","MID1024","Business",23);
        Library.getMemberDetails();
boolean member25 = Library.issueBook("Advaith","Raina",9765400025L,"advaith.raina@gmail.com","The Lean Startup","MID1025","Business",20);
        Library.getMemberDetails();
boolean member26 = Library.issueBook("Meher","Khurana",9012300026L,"meher.khurana@gmail.com","Steve Jobs","MID1026","Biography",21);
        Library.getMemberDetails();
boolean member27 = Library.issueBook("Rishit","Chawla",9345700027L,"rishit.chawla@gmail.com","To Kill a Mockingbird","MID1027","Classic",22);
        Library.getMemberDetails();
boolean member28 = Library.issueBook("Anaya","Bhasin",9876100028L,"anaya.bhasin@gmail.com","The 5 AM Club","MID1028","Self Help",19);
        Library.getMemberDetails();
boolean member29 = Library.issueBook("Yug","Malhotra",9988800029L,"yug.malhotra@gmail.com","Introduction to Algorithms","MID1029","Technology",23);
        Library.getMemberDetails();
boolean member30 = Library.issueBook("Riya","Sodhi",9123400030L,"riya.sodhi@gmail.com","Digital Electronics","MID1030","Education",20);
        Library.getMemberDetails();
boolean member31 = Library.issueBook("Harit","Awasthi",9345800031L,"harit.awasthi@gmail.com","C Programming Language","MID1031","Technology",21);
        Library.getMemberDetails();
boolean member32 = Library.issueBook("Avika","Mehta",9876200032L,"avika.mehta@gmail.com","Database Management System","MID1032","Education",22);
        Library.getMemberDetails();
boolean member33 = Library.issueBook("Eshan","Kapoor",9988900033L,"eshan.kapoor@gmail.com","The Kite Runner","MID1033","Novel",20);
        Library.getMemberDetails();
boolean member34 = Library.issueBook("Kyra","Sachdeva",9123500034L,"kyra.sachdeva@gmail.com","Think Like a Monk","MID1034","Self Help",21);
        Library.getMemberDetails();
boolean member35 = Library.issueBook("Tanish","Grover",9345900035L,"tanish.grover@gmail.com","Introduction to Java","MID1035","Technology",22);
        Library.getMemberDetails();
boolean member36 = Library.issueBook("Aisha","Narang",9876300036L,"aisha.narang@gmail.com","The Secret","MID1036","Motivational",20);
        Library.getMemberDetails();
boolean member37 = Library.issueBook("Rehaan","Pahwa",9988000037L,"rehaan.pahwa@gmail.com","Computer Organization","MID1037","Education",23);
        Library.getMemberDetails();
boolean member38 = Library.issueBook("Navya","Dua",9123600038L,"navya.dua@gmail.com","The Catcher in the Rye","MID1038","Classic",19);
        Library.getMemberDetails();
boolean member39 = Library.issueBook("Vivaan","Bajaj",9345000039L,"vivaan.bajaj@gmail.com","The Intelligent Investor","MID1039","Finance",22);
        Library.getMemberDetails();
boolean member40 = Library.issueBook("Anika","Madan",9876400040L,"anika.madan@gmail.com","Introduction to Python","MID1040","Technology",21);
        Library.getMemberDetails();
boolean member41 = Library.issueBook("Aarohi","Tandon",9988100041L,"aarohi.tandon@gmail.com","The Fault in Our Stars","MID1041","Romance",20);
        Library.getMemberDetails();
boolean member42 = Library.issueBook("Nirvaan","Sengupta",9123700042L,"nirvaan.sengupta@gmail.com","Effective Java","MID1042","Technology",22);
        Library.getMemberDetails();
boolean member43 = Library.issueBook("Mishka","Batra",9345100043L,"mishka.batra@gmail.com","The Power of Positive Thinking","MID1043","Motivational",21);
        Library.getMemberDetails();
boolean member44 = Library.issueBook("Aariz","Khanna",9876500044L,"aariz.khanna@gmail.com","The Odyssey","MID1044","Classic",23);
        Library.getMemberDetails();
boolean member45 = Library.issueBook("Prisha","Kohli",9988200045L,"prisha.kohli@gmail.com","Introduction to SQL","MID1045","Education",19);
        Library.getMemberDetails();
boolean member46 = Library.issueBook("Riaan","Bhagat",9123800046L,"riaan.bhagat@gmail.com","Computer Graphics","MID1046","Technology",22);
        Library.getMemberDetails();
boolean member47 = Library.issueBook("Vanya","Luthra",9345200047L,"vanya.luthra@gmail.com","The Subtle Art of Not Giving a F*ck","MID1047","Self Help",20);
        Library.getMemberDetails();
boolean member48 = Library.issueBook("Atharv","Bhardwaj",9876600048L,"atharv.bhardwaj@gmail.com","The Lord of the Rings","MID1048","Fantasy",21);
        Library.getMemberDetails();
boolean member49 = Library.issueBook("Kiara","Puri",9988300049L,"kiara.puri@gmail.com","Data Mining Concepts","MID1049","Technology",22);
        Library.getMemberDetails();
boolean member50 = Library.issueBook("Devansh","Vashisht",9123900050L,"devansh.vashisht@gmail.com","The Adventures of Sherlock Holmes","MID1050","Mystery",23);
        Library.getMemberDetails();
   }
}